    blank_issues_enabled: false
    contact_links:
      - name: Desktop Fishy Tank on Steam
      about: Store page, Steam discussions and reviews.
      url: https://store.steampowered.com/app/3592010/
